#!/bin/bash

# Define the payload1
payload="$(echo -n '{"csv_content": "WWVhcixJbmR1c3RyeV9hZ2dyZWdhdGlvbl9OWlNJT0MsSW5kdXN0cnlfY29kZV9OWlNJT0MsSW5kdXN0cnlfbmFtZV9OWlNJT0MsVW5pdHMsVmFyaWFibGVfY29kZSxWYXJpYWJsZV9uYW1lLFZhcmlhYmxlX2NhdGVnb3J5LFZhbHVlLEluZHVzdHJ5X2NvZGVfQU5aU0lDMDYKMjAyMSxMZXZlbCAxLDk5OTk5LEFsbCBpbmR1c3RyaWVzLERvbGxhcnMgKG1pbGxpb25zKSxIMDEsVG90YWwgaW5jb21lLEZpbmFuY2lhbCBwZXJmb3JtYW5jZSwiNzU3LDUwNCIsIkFOWlNJQzA2IGRpdmlzaW9ucyBBLVMgKGV4Y2x1ZGluZyBjbGFzc2VzIEs2MzMwLCBMNjcxMSwgTzc1NTIsIE83NjAsIE83NzEsIE83NzIsIFM5NTQwLCBTOTYwMSwgUzk2MDIsIGFuZCBTOTYwMykiCjIwMjEsTGV2ZWwgMSw5OTk5OSxBbGwgaW5kdXN0cmllcyxEb2xsYXJzIChtaWxsaW9ucyksSDA0LCJTYWxlcywgZ292ZXJubWVudCBmdW5kaW5nLCBncmFudHMgYW5kIHN1YnNpZGllcyIsRmluYW5jaWFsIHBlcmZvcm1hbmNlLCI2NzQsODkwIiwiQU5aU0lDMDYgZGl2aXNpb25zIEEtUyAoZXhjbHVkaW5nIGNsYXNzZXMgSzYzMzAsIEw2NzExLCBPNzU1MiwgTzc2MCwgTzc3MSwgTzc3MiwgUzk1NDAsIFM5NjAxLCBTOTYwMiwgYW5kIFM5NjAzKSIKMjAyMSxMZXZlbCAxLDk5OTk5LEFsbCBpbmR1c3RyaWVzLERvbGxhcnMgKG1pbGxpb25zKSxIMDUsIkludGVyZXN0LCBkaXZpZGVuZHMgYW5kIGRvbmF0aW9ucyIsRmluYW5jaWFsIHBlcmZvcm1hbmNlLCI0OSw1OTMiLCJBTlpTSUMwNiBkaXZpc2lvbnMgQS1TIChleGNsdWRpbmcgY2xhc3NlcyBLNjMzMCwgTDY3MTEsIE83NTUyLCBPNzYwLCBPNzcxLCBPNzcyLCBTOTU0MCwgUzk2MDEsIFM5NjAyLCBhbmQgUzk2MDMpIgoyMDIxLExldmVsIDEsOTk5OTksQWxsIGluZHVzdHJpZXMsRG9sbGFycyAobWlsbGlvbnMpLEgwNyxOb24tb3BlcmF0aW5nIGluY29tZSxGaW5hbmNpYWwgcGVyZm9ybWFuY2UsIjMzLDAyMCIsIkFOWlNJQzA2IGRpdmlzaW9ucyBBLVMgKGV4Y2x1ZGluZyBjbGFzc2VzIEs2MzMwLCBMNjcxMSwgTzc1NTIsIE83NjAsIE83NzEsIE83NzIsIFM5NTQwLCBTOTYwMSwgUzk2MDIsIGFuZCBTOTYwMykiCjIwMjEsTGV2ZWwgMSw5OTk5OSxBbGwgaW5kdXN0cmllcyxEb2xsYXJzIChtaWxsaW9ucyksSDA4LFRvdGFsIGV4cGVuZGl0dXJlLEZpbmFuY2lhbCBwZXJmb3JtYW5jZSwiNjU0LDQwNCIsIkFOWlNJQzA2IGRpdmlzaW9ucyBBLVMgKGV4Y2x1ZGluZyBjbGFzc2VzIEs2MzMwLCBMNjcxMSwgTzc1NTIsIE83NjAsIE83NzEsIE83NzIsIFM5NTQwLCBTOTYwMSwgUzk2MDIsIGFuZCBTOTYwMyki", "file_name": "file"}' | base64)"

# Invoke the Lambda function
response=$(aws lambda invoke --function-name csv_to_xlsx --payload "$payload" output.txt)

# Check if the function executed successfully
if grep -q "FunctionError" <<< "$response"; then
  echo "Test failed: Function error"
  exit 1
fi

# Read the response from the output file
result=$(cat output.txt)

# Expected result
expected_result='{"statusCode": 200, "body": "Excel file uploaded to S3 successfully",'

# Check if the result matches the expected result
if [[ $result == $expected_result* ]]; then
  echo "Test passed"
  exit 0
else
  echo "Test failed: Unexpected response"
  exit 1
fi
